# infrastructure/aws/cloudformation/main.yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Hallyu-Pomaholic Sync System - Main Stack'

Parameters:
  EnvironmentName:
    Type: String
    Default: production
    AllowedValues:
      - development
      - staging
      - production
    Description: Environment name
  
  DomainName:
    Type: String
    Description: Domain name for the application
    Default: ""
  
  CertificateArn:
    Type: String
    Description: ACM Certificate ARN for HTTPS
    Default: ""

Resources:
  # VPC Stack
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./vpc.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-vpc

  # ECS Stack
  ECSStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: ./ecs.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        VPC: !GetAtt VPCStack.Outputs.VPC
        PrivateSubnet1: !GetAtt VPCStack.Outputs.PrivateSubnet1
        PrivateSubnet2: !GetAtt VPCStack.Outputs.PrivateSubnet2
        PublicSubnet1: !GetAtt VPCStack.Outputs.PublicSubnet1
        PublicSubnet2: !GetAtt VPCStack.Outputs.PublicSubnet2
        SecurityGroup: !GetAtt VPCStack.Outputs.ECSSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-ecs

  # Lambda Stack
  LambdaStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: ./lambda.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        VPC: !GetAtt VPCStack.Outputs.VPC
        PrivateSubnet1: !GetAtt VPCStack.Outputs.PrivateSubnet1
        PrivateSubnet2: !GetAtt VPCStack.Outputs.PrivateSubnet2
        SecurityGroup: !GetAtt VPCStack.Outputs.LambdaSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-lambda

  # SQS Stack
  SQSStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./sqs.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-sqs

  # API Gateway Stack
  APIGatewayStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: 
      - LambdaStack
      - ECSStack
    Properties:
      TemplateURL: ./api-gateway.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        DomainName: !Ref DomainName
        CertificateArn: !Ref CertificateArn
        WebhookLambdaArn: !GetAtt LambdaStack.Outputs.WebhookHandlerArn
        ALBDNSName: !GetAtt ECSStack.Outputs.ALBDNSName
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-api-gateway

  # Monitoring Stack
  MonitoringStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./monitoring.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        ECSClusterName: !GetAtt ECSStack.Outputs.ClusterName
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-monitoring

Outputs:
  APIEndpoint:
    Description: API Gateway endpoint URL
    Value: !GetAtt APIGatewayStack.Outputs.APIEndpoint
  
  ALBEndpoint:
    Description: Application Load Balancer endpoint
    Value: !GetAtt ECSStack.Outputs.ALBEndpoint

